<a href="https://colab.research.google.com/github/paulgureghian/Google_Colab_Notebooks/blob/master/Single_layer_neural_network_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

** Created by Paul A. Gureghian on 11/19/18.**  
** This notebook contains the code for a single layer neural network in Pytorch.**


In [174]:
### install pytorch and torchvision
!pip3 install -U -q http://download.pytorch.org/whl/cu92/torch-0.4.1-cp36-cp36m-linux_x86_64.whl
!pip3 install -U -q torchvision 

tcmalloc: large alloc 1073750016 bytes == 0x5766a000 @  0x7f1156d972a4 0x591a07 0x5b5d56 0x502e9a 0x506859 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x504c28 0x502540 0x502f3d 0x507641


In [0]:
### import packages 
import torch 
import numpy as np
import torchvision

In [0]:
### define activation function
def activation(x):
    return 1 /  (1 + torch.exp(-x)) 

In [0]:
### generate some data 
torch.manual_seed(7)
features = torch.randn((1, 3))
weights = torch.randn_like(features)
bias = torch.randn((1, 1))

In [178]:
### make labels for the data and weights 
y = activation(torch.sum(features * weights) + bias)
print(y) 
### or 
### y = activation((weights * features).sum() +  bias) 

tensor([[0.5720]])


In [179]:
### calculate the output of the network with matrix multiplication
y = activation(torch.mm(features, weights.view(3,1)) + bias)  
print(y) 

tensor([[0.5720]])


In [0]:
### define the size of each layer in the network
n_input = features.shape[1]
n_hidden = 2
n_output = 1

In [0]:
### weights for inputs to hidden layer
W1 = torch.randn((n_input, n_hidden)) 
### weights for hidden layer to output layer
W2 = torch.randn((n_hidden, n_output))  

In [0]:
### bias terms for hidden and output layers 
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))   

In [183]:
### calculate the network output 
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2) 
print(output) 

tensor([[0.8371]])


In [184]:
!pip freeze

absl-py==0.6.1
altair==2.2.2
astor==0.7.1
atomicwrites==1.2.1
attrs==18.2.0
beautifulsoup4==4.6.3
bleach==3.0.2
cachetools==3.0.0
certifi==2018.10.15
chardet==3.0.4
crcmod==1.7
cycler==0.10.0
cymem==2.0.2
cytoolz==0.9.0.1
decorator==4.3.0
defusedxml==0.5.0
dill==0.2.8.2
entrypoints==0.2.3
future==0.16.0
gast==0.2.0
google-api-core==1.5.2
google-api-python-client==1.6.7
google-auth==1.4.2
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.2.0
google-cloud-bigquery==1.1.0
google-cloud-core==0.28.1
google-cloud-language==1.0.2
google-cloud-storage==1.8.0
google-cloud-translate==1.3.1
google-colab==0.0.1a1
google-resumable-media==0.3.1
googleapis-common-protos==1.5.5
grpcio==1.15.0
h5py==2.8.0
httplib2==0.11.3
idna==2.6
ipykernel==4.6.1
ipython==5.5.0
ipython-genutils==0.2.0
Jinja2==2.10
joblib==0.13.0
jsonschema==2.6.0
jupyter-client==5.2.3
jupyter-core==4.4.0
Keras==2.2.4
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
Markdown==3.0.1
MarkupSafe==1.1.0
matplotlib==2.1.2
mistune==0.